[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "impending"
version = "0.1.0"
description = "Pending."
requires-python = ">=3.8"
readme = "README.md"

[tool.maturin]
manifest-path = "crates/impending/Cargo.toml"
features = ["pyo3/extension-module"]
module-name = "impending._impl"
include = ["_impending.pth"]
python-source = "python"
strip = true

[project.optional-dependencies]
test = [
  "pytest",
  "uv",
]
