[package]
name = "impending"
version = "0.1.0"
edition = "2021"

[lib]
name = "impending_impl"
crate-type = ["cdylib"]

[features]
extension-module = ["pyo3/extension-module"]

[dependencies]
anyhow = { workspace = true }
pyo3 = { workspace = true, features = ["anyhow"] }
toml = { workspace = true }
impending-config = { path = "../impending-config" }
impending-module-map = { path = "../impending-module-map" }
impending-requirements = { path = "../impending-requirements" }
serde = { workspace = true, features=["derive"] }

[dev-dependencies]
pyo3 = { workspace = true, features = ["auto-initialize"]}

[build-dependencies]
pyo3-build-config = { workspace = true }
